services:
  postgres:
    image: ankane/pgvector:latest
    container_name: synapse-postgres
    environment:
      POSTGRES_DB: synapse_local
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: localdev123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./backend/init_local_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse -d synapse_local"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synapse-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.local
    volumes:
      # Mount code for hot reload
      - ./backend/app:/app/app
      # Mount local file storage
      - ./local_storage:/app/storage
    environment:
      # Override for Docker Compose
      ENVIRONMENT: local
      DATABASE_URL: postgresql+asyncpg://synapse:localdev123@postgres:5432/synapse_local
      STORAGE_BACKEND: local
      LOCAL_STORAGE_PATH: /app/storage
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - synapse-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Frontend calls backend directly (same as production architecture)
        VITE_BACKEND_API_URL: http://localhost:8000
    container_name: synapse-frontend
    ports:
      - "3000:8080"
    networks:
      - synapse-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  synapse-network:
    driver: bridge
