import { Sparkles, Zap, Crown } from 'lucide-react';
import type { PricingPlan } from './PricingCard';

export const plans: PricingPlan[] = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Perfect for individuals just getting started',
    price: 5,
    period: 'month',
    icon: Sparkles,
    features: [
      { text: '1 GB storage', included: true },
      { text: '50 requests per day', included: true },
      { text: 'Email support', included: true },
      { text: 'Priority access', included: false },
      { text: 'Advanced AI models', included: false },
      { text: '3rd party providers', included: false },
      { text: 'Memory Graph', included: false },
      { text: 'Team collaboration', included: false },
      { text: 'Custom integrations', included: false },
      { text: 'Unlimited requests', included: false },
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Ideal for power users and small teams',
    price: 20,
    period: 'month',
    badge: 'Most Popular',
    popular: true,
    icon: Zap,
    features: [
      { text: '100 GB storage', included: true },
      { text: '500 requests per day', included: true },
      { text: 'Priority access', included: true },
      { text: 'Advanced AI models', included: true },
      { text: '3rd party providers', included: true },
      { text: 'Memory Graph', included: true },
      { text: 'Chat support', included: true },
      { text: 'Team collaboration', included: false },
      { text: 'Custom integrations', included: false },
      { text: 'Unlimited requests', included: false },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Complete solution for large organizations',
    price: 200,
    period: 'month',
    badge: 'Best Value',
    icon: Crown,
    features: [
      { text: 'Unlimited storage', included: true },
      { text: 'Unlimited requests', included: true },
      { text: 'Premium AI models', included: true },
      { text: 'Dedicated support team', included: true },
      { text: 'Advanced AI models', included: true },
      { text: '3rd party providers', included: true },
      { text: 'Memory Graph', included: true },
      { text: 'Phone support', included: true },
      { text: 'Team collaboration', included: true },
      { text: 'Custom integrations', included: true },
      { text: 'SLA guarantee', included: true },
    ],
  },
];