// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euabvloqnbuxffrwmljk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YWJ2bG9xbmJ1eGZmcndtbGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzAxODksImV4cCI6MjA3NDQ0NjE4OX0.HNuT5xsfZCwo6kBQsGrBus9Jp3OTRbfOFsvsLAR4ahQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});