"""
OpenAI Container File Service.

This module provides functionality to download files generated by OpenAI's
code interpreter from containers.
"""
from typing import Tuple
import logging
import httpx

from .base import OpenAIBaseService

logger = logging.getLogger(__name__)


class ContainerFileService(OpenAIBaseService):
    """Service for downloading files from OpenAI code interpreter containers."""

    async def download_container_file(
        self,
        container_id: str,
        file_id: str,
        filename: str = None
    ) -> Tuple[bytes, str]:
        """
        Download a file from an OpenAI code interpreter container.

        Args:
            container_id: The container ID (e.g., "cntr_...")
            file_id: The file ID (e.g., "cfile_...")

        Returns:
            Tuple of (file_bytes, filename)

        Raises:
            ValueError: If container_id or file_id is invalid
            httpx.HTTPStatusError: If the request fails
            Exception: For other download errors
        """
        self.validate_configuration()

        if not container_id or not file_id:
            raise ValueError("container_id and file_id are required")

        # Construct the URL for downloading file content
        url = f"https://api.openai.com/v1/containers/{container_id}/files/{file_id}/content"

        logger.info(f"Downloading file {file_id} from container {container_id}")

        try:
            # Get the underlying httpx client from AsyncOpenAI
            # The AsyncOpenAI client wraps an httpx AsyncClient
            async with httpx.AsyncClient() as http_client:
                headers = {
                    "Authorization": f"Bearer {self.client.api_key}",
                    "User-Agent": "synapse-memory-bay"
                }

                response = await http_client.get(url, headers=headers, timeout=60.0)
                response.raise_for_status()

                file_bytes = response.content
                logger.info(
                    f"Successfully downloaded {filename} "
                    f"({len(file_bytes)} bytes) from container {container_id}"
                )

                if not filename:
                    filename = file_id
                return file_bytes, filename

        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                logger.error(
                    f"File {file_id} not found in container {container_id}"
                )
                raise ValueError(
                    f"File not found in container. "
                    f"Container: {container_id}, File: {file_id}"
                )
            else:
                logger.error(
                    f"HTTP error downloading file {file_id}: {e.response.status_code}"
                )
                raise

        except httpx.RequestError as e:
            logger.error(f"Network error downloading file {file_id}: {e}")
            raise Exception(f"Failed to download file from OpenAI: {e}")

        except Exception as e:
            logger.error(
                f"Unexpected error downloading file {file_id} "
                f"from container {container_id}: {e}",
                exc_info=True
            )
            raise

    def _extract_filename(self, headers: httpx.Headers, file_id: str) -> str:
        """
        Extract filename from response headers or generate default.

        Handles both standard and RFC 5987 encoded filenames:
        - filename="file.csv"
        - filename*=UTF-8''hello_world.csv

        Args:
            headers: HTTP response headers
            file_id: The file ID for fallback naming

        Returns:
            The filename to use
        """
        import urllib.parse

        # Try to get filename from Content-Disposition header
        content_disposition = headers.get("Content-Disposition", "")
        if content_disposition:
            # First try RFC 5987 encoded filename (filename*=UTF-8''...)
            if "filename*=" in content_disposition:
                # Extract filename*=UTF-8''actual_filename.ext
                parts = content_disposition.split("filename*=")
                if len(parts) > 1:
                    # Remove encoding prefix (UTF-8'') and decode
                    encoded_part = parts[1].split(";")[0].strip()
                    if "''" in encoded_part:
                        filename = encoded_part.split("''", 1)[1]
                        # URL decode the filename
                        filename = urllib.parse.unquote(filename)
                        logger.debug(f"Extracted RFC 5987 filename: {filename}")
                        return filename

            # Fall back to standard filename= parameter
            if "filename=" in content_disposition:
                parts = content_disposition.split("filename=")
                if len(parts) > 1:
                    # Get first part before semicolon and strip quotes
                    filename = parts[1].split(";")[0].strip('"\'').strip()
                    logger.debug(f"Extracted standard filename: {filename}")
                    return filename

        # Fallback: use file_id as filename
        logger.debug(f"No filename in header, using file_id: {file_id}")
        return file_id

    async def get_file_metadata(
        self,
        container_id: str,
        file_id: str
    ) -> dict:
        """
        Retrieve metadata about a file in a container.

        Args:
            container_id: The container ID
            file_id: The file ID

        Returns:
            Dict with file metadata (filename, size, etc.)

        Raises:
            ValueError: If container_id or file_id is invalid
            Exception: For API errors
        """
        self.validate_configuration()

        if not container_id or not file_id:
            raise ValueError("container_id and file_id are required")

        url = f"https://api.openai.com/v1/containers/{container_id}/files/{file_id}"

        logger.debug(f"Fetching metadata for file {file_id} in container {container_id}")

        try:
            async with httpx.AsyncClient() as http_client:
                headers = {
                    "Authorization": f"Bearer {self.client.api_key}",
                    "User-Agent": "synapse-memory-bay"
                }

                response = await http_client.get(url, headers=headers, timeout=30.0)
                response.raise_for_status()

                metadata = response.json()
                logger.debug(f"Retrieved metadata for file {file_id}: {metadata}")

                return metadata

        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error fetching file metadata: {e.response.status_code}")
            raise

        except Exception as e:
            logger.error(f"Error fetching file metadata: {e}", exc_info=True)
            raise


# Singleton instance
container_file_service = ContainerFileService()
